[build]
builder = "nixpacks"

[env]
JAVA_VERSION = "17"

[[services]]
name = "web"
startCommand = "java -jar target/final_project-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "db"
image = "postgres:15" 